In [1]:
import numpy as np

In [2]:
my_array = np.array([2, 3, 4])
print(my_array)

[2 3 4]

In [3]:
print(type(my_array))
print(type(my_array[0]))
print(my_array.dtype)

num = int(my_array[0])
print(type(num))

<class 'numpy.ndarray'>
<class 'numpy.int32'>
int32
<class 'int'>

In [4]:
my_array = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(my_array)
print(my_array.size)
print(my_array.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
12
(3, 4)

In [5]:
a1 = np.reshape(my_array, (1, 12))
print(a1)
a1 = np.reshape(my_array, (12,))
print(a1)
print(a1.size)
print(a1.shape)

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
12
(12,)

In [6]:
print(my_array)
a1 = np.reshape(my_array, (2, -1), order='C')
print(a1)
print(a1.size)
print(a1.shape)
a1 = np.reshape(my_array, (2, 6), order='F')
print(a1)
print(a1.size)
print(a1.shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
12
(2, 6)
[[ 1  9  6  3 11  8]
 [ 5  2 10  7  4 12]]
12
(2, 6)

In [7]:
print(my_array)
a2 = my_array.flatten()
print(a2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]

In [9]:
print(np.zeros((3, 5), dtype=np.float64))
print(np.ones((3, 5), dtype=np.int32))
print(np.full((3, 5), 5, dtype=np.int32))
print(np.empty((3, 5)))

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

In [10]:
import math
print(np.arange(0, 2, 0.1))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9]

In [11]:
print(np.linspace(0, 2, 21))

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7
 1.8 1.9 2. ]

In [12]:
a1 = np.array([[1, 2, 3], [4, 5, 6]])
a2 = np.array([[7, 8, 9], [10, 11, 12]])

print(a1)
print(a2)
print(np.hstack((a1, a2)))
print(np.vstack((a1, a2)))

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

In [15]:
print(a1)
print(a1[0:, 1])

[[1 2 3]
 [4 5 6]]
[2 5]

In [16]:
a = np.arange(12).reshape(3, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

In [17]:
i = np.array([[0, 1], [1, 2]])
j = np.array([[2, 1], [3, 3]])

In [18]:
print(a[i, j])

[[ 2  5]
 [ 7 11]]

In [21]:
a = np.arange(12).reshape(3, 4)
print(a)
b = a > 4
print(b)
print(a[b])
a[b] = 0
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]
[ 5  6  7  8  9 10 11]
[[0 1 2 3]
 [4 0 0 0]
 [0 0 0 0]]

In [22]:
a1 = np.array([[1, 2, 3], [4, 5, 6]])
a2 = np.array([[7, 8, 9], [10, 11, 12]])
print(a1)
print(a2)
print(a1 + a2)
print(a1 * 3)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[ 8 10 12]
 [14 16 18]]
[[ 3  6  9]
 [12 15 18]]

In [28]:
a1 = np.array([[1, 8, 2], [7, 3, 6]])
print(a1)
print(np.min(a1, axis=1))

[[1 8 2]
 [7 3 6]]
[1 3]

In [29]:
a = np.arange(12).reshape(3, 4)
b = a
b[0, 0] = 100
print(b)
print(a)

[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]
[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]

In [30]:
a = np.arange(12).reshape(3, 4)
b = a.view()
b[0, 0] = 100
print(b)
print(a)

[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]
[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]

In [31]:
a = np.arange(12).reshape(3, 4)
b = a.copy()
b[0, 0] = 100
print(b)
print(a)

[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

In [32]:
import pandas as pd

In [33]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
print(s)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [34]:
dates = pd.date_range("20230101", periods=6)
print(dates)

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06'],
              dtype='datetime64[ns]', freq='D')

In [35]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=["C1", "C2", "C3", "C4"])
print(df)

                  C1        C2        C3        C4
2023-01-01  1.611370  0.332061  0.863266 -0.354273
2023-01-02  0.525551 -0.895722 -0.514368  0.700955
2023-01-03 -1.687421 -0.672188  0.124262 -0.553449
2023-01-04  0.283752 -0.124378  1.722799  0.982769
2023-01-05  1.023180  1.244945 -0.128426  0.161780
2023-01-06  0.111526 -0.183041  1.576549  0.665338

In [36]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)
print(df2)

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [37]:
print(df)

                  C1        C2        C3        C4
2023-01-01  1.611370  0.332061  0.863266 -0.354273
2023-01-02  0.525551 -0.895722 -0.514368  0.700955
2023-01-03 -1.687421 -0.672188  0.124262 -0.553449
2023-01-04  0.283752 -0.124378  1.722799  0.982769
2023-01-05  1.023180  1.244945 -0.128426  0.161780
2023-01-06  0.111526 -0.183041  1.576549  0.665338

In [38]:
print(df["C1"])
print(df.C1)

2023-01-01    1.611370
2023-01-02    0.525551
2023-01-03   -1.687421
2023-01-04    0.283752
2023-01-05    1.023180
2023-01-06    0.111526
Freq: D, Name: C1, dtype: float64
2023-01-01    1.611370
2023-01-02    0.525551
2023-01-03   -1.687421
2023-01-04    0.283752
2023-01-05    1.023180
2023-01-06    0.111526
Freq: D, Name: C1, dtype: float64

In [39]:
print(df[0:3])

                  C1        C2        C3        C4
2023-01-01  1.611370  0.332061  0.863266 -0.354273
2023-01-02  0.525551 -0.895722 -0.514368  0.700955
2023-01-03 -1.687421 -0.672188  0.124262 -0.553449

In [40]:
print(df["2023-01-01":"2023-01-04"])

                  C1        C2        C3        C4
2023-01-01  1.611370  0.332061  0.863266 -0.354273
2023-01-02  0.525551 -0.895722 -0.514368  0.700955
2023-01-03 -1.687421 -0.672188  0.124262 -0.553449
2023-01-04  0.283752 -0.124378  1.722799  0.982769

In [41]:
print(df.loc["2023-01-01":"2023-01-04", ["C2", "C4"]])
print(df.at["2023-01-01", "C2"])

                  C2        C4
2023-01-01  0.332061 -0.354273
2023-01-02 -0.895722  0.700955
2023-01-03 -0.672188 -0.553449
2023-01-04 -0.124378  0.982769
0.33206106509451117

In [42]:
print(df.iloc[0:4, [1, 3]])
print(df.iat[0, 1])

                  C2        C4
2023-01-01  0.332061 -0.354273
2023-01-02 -0.895722  0.700955
2023-01-03 -0.672188 -0.553449
2023-01-04 -0.124378  0.982769
0.33206106509451117

In [43]:
print(df)

                  C1        C2        C3        C4
2023-01-01  1.611370  0.332061  0.863266 -0.354273
2023-01-02  0.525551 -0.895722 -0.514368  0.700955
2023-01-03 -1.687421 -0.672188  0.124262 -0.553449
2023-01-04  0.283752 -0.124378  1.722799  0.982769
2023-01-05  1.023180  1.244945 -0.128426  0.161780
2023-01-06  0.111526 -0.183041  1.576549  0.665338

In [44]:
print(df[df.C3 < 0])

                  C1        C2        C3        C4
2023-01-02  0.525551 -0.895722 -0.514368  0.700955
2023-01-05  1.023180  1.244945 -0.128426  0.161780

In [45]:
df2.loc[3, "E"] = np.nan

In [46]:
print(df2)

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3    NaN  foo

In [47]:
print(df2[df2["E"].isin(["test", "train"])])

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo

In [48]:
df2["G"] = 0

In [49]:
print(df2)

     A          B    C  D      E    F  G
0  1.0 2013-01-02  1.0  3   test  foo  0
1  1.0 2013-01-02  1.0  3  train  foo  0
2  1.0 2013-01-02  1.0  3   test  foo  0
3  1.0 2013-01-02  1.0  3    NaN  foo  0

In [50]:
df2["H"] = [0, 1, 2, 3]
print(df2)

     A          B    C  D      E    F  G  H
0  1.0 2013-01-02  1.0  3   test  foo  0  0
1  1.0 2013-01-02  1.0  3  train  foo  0  1
2  1.0 2013-01-02  1.0  3   test  foo  0  2
3  1.0 2013-01-02  1.0  3    NaN  foo  0  3

In [51]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=["C1", "C2", "C3", "C4"])
print(df)
df[df < 0] = -df
print(df)

                  C1        C2        C3        C4
2023-01-01  0.400989  0.824190 -0.216674 -0.209303
2023-01-02 -2.349091 -0.335568 -0.197483 -0.245668
2023-01-03 -0.697473  1.058731  0.909379 -0.254442
2023-01-04 -0.573182 -0.670558  0.019950 -0.290055
2023-01-05 -0.565316 -0.234718  3.697273  1.129873
2023-01-06  0.680908  0.140445 -0.595322  0.037913
                  C1        C2        C3        C4
2023-01-01  0.400989  0.824190  0.216674  0.209303
2023-01-02  2.349091  0.335568  0.197483  0.245668
2023-01-03  0.697473  1.058731  0.909379  0.254442
2023-01-04  0.573182  0.670558  0.019950  0.290055
2023-01-05  0.565316  0.234718  3.697273  1.129873
2023-01-06  0.680908  0.140445  0.595322  0.037913

In [52]:
print(df.index)
print(df.columns)

DatetimeIndex(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04',
               '2023-01-05', '2023-01-06'],
              dtype='datetime64[ns]', freq='D')
Index(['C1', 'C2', 'C3', 'C4'], dtype='object')

In [53]:
print(df.to_numpy())

[[0.40098899 0.82418993 0.21667392 0.20930301]
 [2.34909113 0.33556842 0.19748288 0.24566763]
 [0.69747259 1.05873064 0.90937852 0.25444181]
 [0.57318157 0.6705575  0.01994966 0.29005484]
 [0.56531584 0.23471783 3.697273   1.12987261]
 [0.68090777 0.140445   0.59532181 0.03791306]]

In [54]:
a = df2.to_numpy()
print(a.dtype)

object

In [55]:
df.describe()

             C1        C2        C3        C4
count  6.000000  6.000000  6.000000  6.000000
mean   0.877826  0.544035  0.939347  0.361209
std    0.728529  0.363711  1.388763  0.386847
min    0.400989  0.140445  0.019950  0.037913
25%    0.567282  0.259930  0.202281  0.218394
50%    0.627045  0.503063  0.405998  0.250055
75%    0.693331  0.785782  0.830864  0.281152
max    2.349091  1.058731  3.697273  1.129873

In [56]:
print(df)
print(df.T)

                  C1        C2        C3        C4
2023-01-01  0.400989  0.824190  0.216674  0.209303
2023-01-02  2.349091  0.335568  0.197483  0.245668
2023-01-03  0.697473  1.058731  0.909379  0.254442
2023-01-04  0.573182  0.670558  0.019950  0.290055
2023-01-05  0.565316  0.234718  3.697273  1.129873
2023-01-06  0.680908  0.140445  0.595322  0.037913
    2023-01-01  2023-01-02  2023-01-03  2023-01-04  2023-01-05  2023-01-06
C1    0.400989    2.349091    0.697473    0.573182    0.565316    0.680908
C2    0.824190    0.335568    1.058731    0.670558    0.234718    0.140445
C3    0.216674    0.197483    0.909379    0.019950    3.697273    0.595322
C4    0.209303    0.245668    0.254442    0.290055    1.129873    0.037913

In [57]:
print(df)

                  C1        C2        C3        C4
2023-01-01  0.400989  0.824190  0.216674  0.209303
2023-01-02  2.349091  0.335568  0.197483  0.245668
2023-01-03  0.697473  1.058731  0.909379  0.254442
2023-01-04  0.573182  0.670558  0.019950  0.290055
2023-01-05  0.565316  0.234718  3.697273  1.129873
2023-01-06  0.680908  0.140445  0.595322  0.037913

In [58]:
print(df.sort_values(by="C2"))

                  C1        C2        C3        C4
2023-01-06  0.680908  0.140445  0.595322  0.037913
2023-01-05  0.565316  0.234718  3.697273  1.129873
2023-01-02  2.349091  0.335568  0.197483  0.245668
2023-01-04  0.573182  0.670558  0.019950  0.290055
2023-01-01  0.400989  0.824190  0.216674  0.209303
2023-01-03  0.697473  1.058731  0.909379  0.254442

In [59]:
print(df2)

     A          B    C  D      E    F  G  H
0  1.0 2013-01-02  1.0  3   test  foo  0  0
1  1.0 2013-01-02  1.0  3  train  foo  0  1
2  1.0 2013-01-02  1.0  3   test  foo  0  2
3  1.0 2013-01-02  1.0  3    NaN  foo  0  3

In [60]:
print(pd.isna(df2))

       A      B      C      D      E      F      G      H
0  False  False  False  False  False  False  False  False
1  False  False  False  False  False  False  False  False
2  False  False  False  False  False  False  False  False
3  False  False  False  False   True  False  False  False

In [61]:
df2.dropna()

     A          B    C  D      E    F  G  H
0  1.0 2013-01-02  1.0  3   test  foo  0  0
1  1.0 2013-01-02  1.0  3  train  foo  0  1
2  1.0 2013-01-02  1.0  3   test  foo  0  2

In [62]:
print(df2)

     A          B    C  D      E    F  G  H
0  1.0 2013-01-02  1.0  3   test  foo  0  0
1  1.0 2013-01-02  1.0  3  train  foo  0  1
2  1.0 2013-01-02  1.0  3   test  foo  0  2
3  1.0 2013-01-02  1.0  3    NaN  foo  0  3

In [63]:
df2.fillna(value="train")

     A          B    C  D      E    F  G  H
0  1.0 2013-01-02  1.0  3   test  foo  0  0
1  1.0 2013-01-02  1.0  3  train  foo  0  1
2  1.0 2013-01-02  1.0  3   test  foo  0  2
3  1.0 2013-01-02  1.0  3  train  foo  0  3